name: Widget tests & code analysis

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.json'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.json'
  schedule:
    - cron: '0 4 * * 2'
  workflow_dispatch:

# https://admcpr.com/continuous-integration-for-flutter-with-github-actions/
jobs:
  test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    # Use the community Action to install Flutter
    - uses: subosito/flutter-action@v1
    - name: Version
      run: flutter doctor -v
    - name: Install dependencies
      run: flutter pub get
    - name: Format
      run: flutter format -n --set-exit-if-changed .
    - name: Linter
      run: flutter analyze
    - name: Test
      run: flutter test
