name: Widget tests & code analysis

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.json'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.json'
  schedule:
    - cron: '0 4 * * 2'
  workflow_dispatch:

# https://admcpr.com/continuous-integration-for-flutter-with-github-actions/
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
        cache-key: flutter
        cache-path: ${{ runner.tool_cache }}/flutter
    
    - name: Version
      run: flutter doctor -v
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Format
      run: flutter format -n --set-exit-if-changed .
    
    - name: Linter
      run: flutter analyze
    
    - name: Test
      run: flutter test

  build-self-hosted:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Test
      run: docker run --rm -it -v ${PWD}:/build --workdir /build cirrusci/flutter:stable flutter test
